### ISSUE TITLE
2020.05.09 宕机报告

### ISSUE THREAD

**Issue by ChiruMori** [first-snow/baka#1]
## 服务器启动一段时间后，在日志中发现如下问题，且持续报出，直到日志文件耗尽系统硬盘：

> [2020.05.08 20:59:07] work.cxlm.main.SubReactor:103_run - [异常终止: Index 1 out of bounds for length 1]
> java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
> 	at work.cxlm.http.HttpRequest.resolve(HttpRequest.java:118)
> 	at work.cxlm.main.SubReactor.run(SubReactor.java:77)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:830)
> [2020.05.08 20:59:07] work.cxlm.main.SubReactor:103_run - [异常终止: Index 1 out of bounds for length 1]
> java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
> 	at work.cxlm.http.HttpRequest.resolve(HttpRequest.java:118)
> 	at work.cxlm.main.SubReactor.run(SubReactor.java:77)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by first-snow** [comment]
修复后再未爆出，通过日志分析为搜索引擎爬虫导致
